Get into hubflow shape
dockstore/dockstore-documentation pull request #116
Opened 2021-06-15 15:45 UTC by denis-yuen

2021-06-15 17:01 UTC, coverbeck approved these changes
This will affect the main docs, i.e., the doc linked to from 1.10. Were you going to merge this before the 1.11 release?

2021-06-15 17:35 UTC, denis-yuen commented
> This will affect the main docs, i.e., the doc linked to from 1.10. Were you going to merge this before the 1.11 release?

No, think we have to do this after release as with https://github.com/dockstore/extra-content/pull/23
Maybe you should put in a blocking review just in case we forget

2021-06-15 17:38 UTC, coverbeck requested changes
Looks good, but blocking until 1.11 release.

2021-06-15 20:52 UTC, david4096 approved these changes

2021-06-15 22:54 UTC, NatalieEO approved these changes

2021-07-14 21:05 UTC, coverbeck approved these changes

2021-07-14 21:05 UTC, merged