Subtly clarify .dockstore.yml `filter` is not about Docker tags
dockstore/dockstore-documentation pull request #195
Opened 2022-04-20 17:33 UTC by aofarrel

Neither this version nor the old one mention Docker tags at all, but I think users new to Docker and git have a chance of getting the two mixed up. I swapped the order of the words and added "GitHub" right before "tags" in attempt to make it clearer, as well as linked GitHub's own docs on the two. Also included a sentence reminding users that they need to have their workflow/tool/service on Dockstore, just in case a user goes straight here without reading any of our other docs.

2022-04-20 23:38 UTC, aofarrel commented
<img width="818" alt="Screen Shot 2022-04-20 at 4 38 01 PM" src="https://user-images.githubusercontent.com/27784612/164341704-6c3087ce-d42b-47b6-b035-28c5ebc127c7.png">

...hmmmmmmm.

<img width="1101" alt="Screen Shot 2022-04-20 at 4 36 04 PM" src="https://user-images.githubusercontent.com/27784612/164341641-b4e50716-0b46-42a9-96ad-f65688b0af83.png">

2022-04-20 23:51 UTC, aofarrel commented
Did a search of the packages that were updated between the CI builds I pulled these from, not seeing any issues about attrs not getting installed.

2022-04-21 23:42 UTC, coverbeck approved these changes
A little confused why requirements.txt is needed all of the sudden. Is it because we're not pinning all our requirements.

Going to defer to @Richard-Hansen or any other Python people he wants to bring in, but text changes look good.

2022-04-21 23:48 UTC, coverbeck requested changes
I built this locally and the links don't look right, I think you've done markdown

![Screen Shot 2022-04-21 at 4 47 14 PM](https://user-images.githubusercontent.com/1049340/164568813-12708210-1607-46a9-bbbc-e085901f4a2b.png)

2022-04-26 16:12 UTC, Richard-Hansen approved these changes
After link change suggested by Charles.

2022-04-26 18:04 UTC, aofarrel commented
> > A little confused why requirements.txt is needed all of the sudden. Is it because we're not pinning all our requirements.
> > Going to defer to @Richard-Hansen or any other Python people he wants to bring in, but text changes look good.
> 
> I'm not seeing why our dependencies changed requirements. Our versions are pinned and the git repo hasn't changed in quite a while. Perhaps some deep-down transitive dependency? Regardless, probably nothing to do on our end.

Our versions are pinned, but their own dependencies presumably are not themselves pinned. For example, an older build installed mdurl-0.1.0 while a newer one installed mdurl-0.1.1 so I'm lead to believe that some dependency of a dependency is not installing a dependency of that dependency's dependency. Given the error is in myst_parser it is probably one of its dependencies but I checked the packages that have been updated between the two builds screenshot above, and didn't find the culprit, nor did I find people reporting issues... so I'm just pinning attrs in our own requirements.txt whilst shrugging.

2022-04-26 19:52 UTC, coverbeck commented
> Our versions are pinned, but their own dependencies presumably are not themselves pinned. For example, an older build installed mdurl-0.1.0 while a newer one installed mdurl-0.1.1 so I'm lead to believe that some dependency of a dependency is not installing a dependency of that dependency's dependency. Given the error is in myst_parser it is probably one of its dependencies but I checked the packages that have been updated between the two builds screenshot above, and didn't find the culprit, nor did I find people reporting issues... so I'm just pinning attrs in our own requirements.txt whilst shrugging.

Speaking in general terms, it's odd to me that all transitive dependencies are not captured in the requirements.txt file. In the npm/JavaScript world they are.

If transitive dependencies aren't captured, then the requirements.txt is going to be prone to breakage.

2022-04-26 19:55 UTC, coverbeck approved these changes

2022-04-26 20:22 UTC, merged