Warning
dockstore/dockstore-documentation pull request #80
Opened 2020-09-15 18:43 UTC by garyluu

Part 1 of https://github.com/dockstore/dockstore/issues/3790 , Add simple warning when setting the descriptor language

2020-09-15 19:27 UTC, coverbeck approved these changes

2020-09-15 19:32 UTC, NatalieEO approved these changes

2020-09-16 16:06 UTC, wshands approved these changes

2020-09-18 20:48 UTC, denis-yuen requested changes
Confirm intended targets for PRs. 
It looks like this warning is for develop but the new endpoint is to 1.9.2 hotfix. Is this reversed?

2020-09-18 22:49 UTC, garyluu commented
> Confirm intended targets for PRs.
> It looks like this warning is for develop but the new endpoint is to 1.9.2 hotfix. Is this reversed?

I mentioned that the new endpoint draft PR needs to change the base. As for this PR...the prod website docs link points to develop.

2020-09-21 15:34 UTC, denis-yuen approved these changes

2020-09-23 18:34 UTC, merged